/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Spinner__factory } from "./Spinner__factory";
export { SpinnerNew__factory } from "./SpinnerNew__factory";
